spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/codigo_booking_db
spring.datasource.username=root
spring.datasource.password=root

spring.data.redis.host=localhost
spring.data.redis.port=6379

com.codigo.jwt.secret=7N/+nor6L4ckj/gcvCWPsxyjr34VGNMB7xAq0CzqiuQ=

spring.jpa.show-sql=true